spring.application.name=travel-agent

spring.datasource.url=jdbc:postgresql://localhost:5432/travel_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

logging.level.org.springframework.security=DEBUG

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=Travel Agent
info.app.version=1.0
info.app.description=Spring Boot Travel Management System